project:
  type: website

listing:
  contents: posts
  feed: true

website:
  site-url: "https://r-causal.github.io/r-causal-blog/"
  title: "Causal Inference in R"
  navbar:
    right:
      - text: "Read the Book"
        href: https://www.r-causal.org/
      - posts.qmd
      - courses.qmd
      - about.qmd
      - icon: github
        href: https://github.com/r-causal
format:
  html:
    theme: [lumen, styles.scss]
    css: styles.css
    include-after-body: plausible.html

editor: visual

