project:
  type: website

website:
  title: "Causal Inference in R"
  navbar:
    right:
      - text: "Read the Book"
        href: https://www.r-causal.org/
      - posts.qmd
      - courses.qmd
      - about.qmd
      - icon: github
        href: https://github.com/r-causal
format:
  html:
    theme: [lumen, styles.scss]
    css: styles.css

editor: visual

